name: Run unit test for all available tests
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: volta-cli/action@v4
      - name: Print node/npm/yarn info
        id: info
        run: |
          node_ver=$( node --version )
          yarn_ver=$( yarn --version )
          echo "Node: ${node_ver:1}"
          echo "NPM: $( npm --version )"
          echo "Yarn: $yarn_ver"
          echo "node_version=${node_ver:1}" >> $GITHUB_OUTPUT
          echo "yarn_version=${yarn_ver}" >> $GITHUB_OUTPUT
          echo "cache_dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Use yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.info.outputs.cache_dir }}
          key: ${{ runner.os }}-node-${{ steps.info.outputs.node_version }}-yarn-${{ steps.info.outputs.yarn_version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.info.outputs.node_version }}-yarn-${{ steps.info.outputs.yarn_version }}-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run unit tests
        run: yarn test-all